### ISSUE TITLE
Create/Support Playnite Addon

### ISSUE THREAD

**Issue by trymeouteh** [RobLoach/lutris-kodi-addon#51]
Playnite is a free open source game library for Windows, it is essentially Lutris on Windows which does support emulators and PC games. Please consider making an addon for Playnite or adding Playnite support into this addon.

https://playnite.link/

**Comment by RobLoach** [comment]
That would be awesome!

**Comment by solbero** [comment]
Unfortunately it looks like it is not possible to create a similar addon for Playnite. When I looked over the documentation it seems like it is a GUI application only. Since it is missing a way to interact with it through the command line making an addon similar to kodi-lutris-addon will be very hard.
